---
- hosts: all
  vars:
    gitrepo: https://github.com/bortolo/javawebapp.git #https://github.com/bortolo/mainappTodolilst.git #https://github.com/bortolo/javawebapp.git #
    host_user: myadmin
    path_for_the_app: "/home/{{host_user}}/todolistapp"

  tasks:
    - name: Pull file from source
      git:
        repo: "{{gitrepo}}"
        dest: "{{path_for_the_app}}"
    - name: Copy war file in webapps directory
      command: sudo cp target/my-real-app-war.war /var/lib/tomcat8/webapps #sudo cp HelloWorldServlet.war /var/lib/tomcat8/webapps #sudo cp HelloWorldServlet.war /var/lib/tomcat8/webapps #sudo cp target/my-real-app-war.war /var/lib/tomcat8/webapps #sudo cp HelloWorldServlet.war /var/lib/tomcat8/webapps
      become: yes
      become_user: myadmin
      args:
       chdir: "{{path_for_the_app}}"
