---
- hosts: all

  vars:
    - homeDir: /home/myadmin
    - appDir : todolistapp
    - repo: 'https://github.com/bortolo/Todolist.git'

  tasks:
    - name: Create APP Directory
      file: path={{homeDir}}/{{appDir}} state=directory
    - name: Pull file from source
      git: repo={{repo}} dest={{homeDir}}/{{appDir}}
    - name: Start APP
      command: node app.js &
      args:
       chdir: {{homeDir}}/{{appDir}}
