---
- hosts: all
  vars:
    gitrepo: https://github.com/bortolo/Todolist.git
    host_user: myadmin
    path_for_the_app: "/home/{{host_user}}/todolistapp"

  tasks:
    - name: Pull file from source
      git:
        repo: "{{gitrepo}}"
        dest: "{{path_for_the_app}}"
    - name: Move systemctl config file
      become: yes
      become_user: root
      copy:
       src: "{{path_for_the_app}}/todolistapp.service"
       dest: /lib/systemd/system/todolistapp.service
       remote_src: yes
    - name: Update systemd daemon
      become: yes
      become_user: root
      command: systemctl daemon-reload
    - name: "Make sure todolistapp is stopped"
      command: "sudo systemctl stop todolistapp.service"
    - name: "Make sure todolistapp is started"
      command: "sudo systemctl start todolistapp.service"
