---
- hosts: all
  tasks:
    - name: Create new ssh key-pair
      local_action: command ssh-keygen -t rsa -N “” -q -f ~/.ssh/id_ssh_rsa
    - name: Set up authorized_keys for the users
      authorized_key:
       user: myadmin
       key: ”{{ item }}”
       state: present
       exclusive: yes
       with_file:
         - ~/.ssh/id_ssh_rsa.pub
    - name: move key-pair
      local_action: command mv ~/.ssh/id_ssh_rsa ~/.ssh/id_ssh_rsa.bak
      run_once: true
    - name: move key-pair
      local_action: command mv ~/.ssh/id_ssh_rsa.pub ~/.ssh/id_ssh_rsa.pub.bak
      run_once: true
